import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Soltec Test 🪄",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Prueba Técnica - Next.js 14</title>
      </head>
      <body>
        <Providers>
          <div className="layout">
            <nav className="sidebar">
              <ul>
                <li>
                  <Link href="/">Inicio</Link>
                </li>
                <li>
                  <Link href="/users">Usuarios</Link>
                </li>
                <li>
                  <Link href="/posts">Publicaciones</Link>
                </li>
              </ul>
            </nav>
            <main className="content">{children}</main>
          </div>
          <footer className="footer">
            <p>Developed by CCC</p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
