import type { Metadata } from "next";
import TanstacQueryProvider from "./TanstacQueryProvider";
import Sidebar from "./components/Sidebar";

import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Solnec Test 🪄",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <link rel="preload" as="image" href="/images/programmer-girl.png" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Prueba Técnica - Next.js 14</title>
      </head>
      <body>
        <TanstacQueryProvider>
          <div className="layout">
            <Sidebar />
            <main className="content">{children}</main>
          </div>
          <footer className="footer">
            <p>Developed by Carolina Colorado 👩🏻‍💻</p>
          </footer>
        </TanstacQueryProvider>
      </body>
    </html>
  );
}
